// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7fBNJGwIi9Nqtbp_lNZ8yCahHsAmfpJk',
    appId: '1:821363705771:web:43d20103ba5a2ce91334ee',
    messagingSenderId: '821363705771',
    projectId: 'dreamteam-a6c08',
    authDomain: 'dreamteam-a6c08.firebaseapp.com',
    storageBucket: 'dreamteam-a6c08.appspot.com',
    measurementId: 'G-ZR9XRLH907',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Osc857JZEtj1NdMDgygX_2gdUnfjv5w',
    appId: '1:821363705771:android:5294e5837eaa0d781334ee',
    messagingSenderId: '821363705771',
    projectId: 'dreamteam-a6c08',
    storageBucket: 'dreamteam-a6c08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyWwyirZcjaPzgNZi1sjz6fGcL2XEooeQ',
    appId: '1:821363705771:ios:18270ba0751208f31334ee',
    messagingSenderId: '821363705771',
    projectId: 'dreamteam-a6c08',
    storageBucket: 'dreamteam-a6c08.appspot.com',
    iosClientId: '821363705771-pvccj6n8fubja56n3mq5bg6agjrfle19.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPlayground',
  );
}
